### ISSUE TITLE
Logging only warnings, Not the Errors

### ISSUE THREAD

**Issue by sumitknoldus** [adrianpietka/jshint-html-reporter#5]
Hi Adrian,

Hope you are doing well.

I am using jshint-html-reporter for my angular project and its really great but, i'm having some problems which are as follows:

1.  The reporter is showing only the warnings in html file no errors. e.g., it showing where the semicolon is missing means if it is in the warning category it will be shown by reporter but if its in the category of error it wont show eg., Missing statements or 'xyz_module' is defined but never used.

2. when I'm running the command "jshint --reporter node_modules/jshint-html-reporter/reporter.js controllers/*.js". it's generating the html in the terminal, its not creating any .html file in any of my folder, I tried grunt-contrib-hint but still its showing all the html content only in the terminal.

I'll be glad if you can help me on this.
Regards

**Comment by adrianpietka** [comment]
@sumitknoldus: thanks! i will investigate it.

**Comment by Leandros** [comment]
It's showing errors for me, did a simple test with `arguments.x = 5;`, which produces the `Bad Assignment` error in `jshint`.
It's just jshint, where nearly everything is just a warning.

**Comment by adrianpietka** [comment]
Hi @sumitknoldus! About your issue:

1) The @Leandros give you right answer.

2) Yes, you are right, JShint print output only to terminal. If you want save it to file, try redirect stdout to file:

```
jshint --reporter node_modules/jshint-html-reporter/reporter.js controllers/*.js > report.html
```
